- package.json
JIRA: https://jira.rax.io/browse/MNRVA-4
> creates initial node package manifest

- gulpfile.js
- package.json
- spec/sample.spec.js
- tasks/jasmine.js
JIRA: https://jira.rax.io/browse/MNRVA-6
Description:
Sets up Jasmine as our unit test framework of choice
Test:
run `npm run test`
> Configures Jasmine as our unit test framework

- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/poc-api-call.service.spec.ts
- src/app/poc-api-call.service.ts
- src/app/poc-data-call/poc-data-call.component.html
- src/app/poc-data-call/poc-data-call.component.spec.ts
- src/app/poc-data-call/poc-data-call.component.ts
**JIRA**: https://jira.rax.io/browse/MNRVA-20
**Description**:
This is a proof of concept for integrating with Metrics V2.  The important thing to remember here is that this PR is basically throw away and will not be a long lasting feature. This is also only creating the service that calls the API. The data visualization will come next.
**Testing**:
Run `ng serve` and when the application loads, look at the JavaScript console in the browser.  You should see the returned response printed.
> Adds a POC intergration with metrics v2

- README.md
- package.json
JIRA: https://jira.rax.io/browse/MNRVA-9
Description:
Refactors the initial developer documentation to be more clear on how to get up and running with this application.  As excepted, documentation is a living document.
Test: 
Run `npm run docs` and view the Readme file in the served compudoc interface
> Flushes out the initial developer documentation

- pull_request_template.md
PR: https://jira.rax.io/browse/MNRVA-38
Description:
Adds PR template for future PRs.  Will not reflect on this one however
> Adds pull request template

- package-lock.json
See ticket here - https://jira.rax.io/browse/MNRVA-49
There is a security vulnerability with a dep of a dep. We reported to the publisher and they released a new version. Hopefully this solves the issue.
> updates lock file

- cloudbuild.yaml
- package.json
- src/karma.conf.js
See ticket here - https://jira.rax.io/browse/MNRVA-XXXX
:(
do tests!
it's the tests
> Making cloudbuild run tests

- src/index.html
N/A
This is an attempt to fix the issue of assets not loading in the staging portal version of Intelligence
> base href fix for portal

- README.md
- angular.json
- cloudbuild-deploy.yaml
- localenv/arguments.js
- localenv/config/index.js
- localenv/config/settings.json
- localenv/helpers/parse.js
- localenv/identity/token.js
- localenv/nodemon.json
- localenv/package-lock.json
- localenv/package.json
- localenv/pilot/index.js
- localenv/server.js
- src/index.html
See ticket here - https://jira.rax.io/browse/MNRVA-306
This allows local mocking of the environments for either `staging` or `production`. Username & password or Username & ApiKey are passed as arguments against `identity.api.rackspacecloud.com` to get auth token and Pilot Nav. 
`cd localenv`
` NODE_ENV=[dev, staging, or prod] npm run dev -- --username [username] --password [password]`
> Mocked env for staging & prod

- cloudbuild-stage-deploy.yaml
See ticket here - https://jira.rax.io/browse/MNRVA-15
- created new cloud build file for staging 
- updated to fix missing files due to base_url change in application
http://mnrva-deploy.stage.monplat.rackspace.net/intelligence/
> Stage branch fix deployment issues

- localenv/api.js
- localenv/helpers/pilot.js
- localenv/helpers/portal.js
- localenv/routes/salus.js
- localenv/server.js
- src/app/_services/resources/resources.service.spec.ts
- src/app/_services/resources/resources.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-310
Lay groundwork for Resource service for related CRUD operations. 
Create backend API for Resource requests when local
`npm run test`
> Resource service shell with local support

- localenv/routes/salus.js
- localenv/server.js
- src/app/_features/resources/components/resources.component.spec.ts
- src/app/_features/resources/components/resources.component.ts
- src/app/_mocks/resources/collection.json
- src/app/_mocks/resources/resources.service.mock.ts
- src/app/_services/resources/resources.service.spec.ts
- src/app/_services/resources/resources.service.ts
- src/environments/environment.mock.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/tsconfig.app.json
- src/tsconfig.spec.json
See ticket here - https://jira.rax.io/browse/MNRVA-311
Service returns mock data and requests resources for a collection.
Items needing to be finalized: 
- structure of response data
- interface or class representing the data model returned
`npm run test`
> resource list service mocks + json compile

- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/pages/details/resource-details.page.html
- src/app/_features/resources/pages/details/resource-details.page.spec.ts
- src/app/_features/resources/pages/details/resource-details.page.ts
- src/app/_features/resources/pages/resources/resources.page.html
- src/app/_features/resources/resources.module.ts
See ticket here - https://jira.rax.io/browse/MNRVA-224
Adds the route and page for the resources details page
`npm run test`
> Resources detail Page route + page

- src/app/_shared/shared.module.ts
- src/app/app.module.ts
See ticket here - https://jira.rax.io/browse/MNRVA-323
Added shared Module for future components that will be available throughout the application. 
N/A
> Add shared module

- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/components/list/resourceslist.component.less
- src/app/_features/resources/components/list/resourceslist.component.spec.ts
- src/app/_features/resources/components/list/resourceslist.component.ts
- src/app/_features/resources/pages/details/resource-details.page.spec.ts
- src/app/_features/resources/pages/resources/resources.page.html
- src/app/_features/resources/pages/resources/resources.page.spec.ts
- src/app/_features/resources/resources.module.ts
- src/app/_shared/shared.module.ts
- src/app/app.component.html
- src/app/app.module.ts
- src/index.html
See ticket here - https://jira.rax.io/browse/MNRVA-313
Markup added for displaying list of resources
`npm run test`
> Add markup & logic for resource list

- src/app/_features/monitors/components/list/monitorslist.component.html
- src/app/_features/monitors/components/list/monitorslist.component.less
- src/app/_features/monitors/components/list/monitorslist.component.spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.ts
- src/app/_features/monitors/monitors.module.ts
- src/app/_features/monitors/pages/monitors/monitors.page.html
- src/app/_features/monitors/pages/monitors/monitors.page.spec.ts
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_mocks/monitors/collection.json
- src/app/_mocks/monitors/monitors.service.mock.ts
- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
- src/environments/environment.mock.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
See ticket here - https://jira.rax.io/browse/MNRVA-221
Monitors list view and accompanying service with mocks for collection
`npm run test` and/or navigating `/monitors`
> Monitors list + service with mocks

- cloudbuild.yaml
- src/app/_features/resources/pages/details/resource-details.page.spec.ts
- src/app/_features/resources/pages/details/resource-details.page.ts
See ticket here - https://jira.rax.io/browse/MNRVA-345
Fix issues with e2e and unit tests failing
you can run this manually by using gcloud command
gcloud builds submit --config cloudbuild.yaml
n/a
> Fix gcb tests mnrva 345

- angular.json
- e2e/src/app.e2e-spec.ts
- e2e/src/app.po.ts
See ticket here - https://jira.rax.io/browse/MNRVA-347
Update build options to work with container based e2e test
`npm run e2e`
> add baseHref to build options

- src/app/_features/monitors/monitors.module.ts
- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/monitors/pages/details/monitor-details.page.less
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_mocks/monitors/monitors.service.mock.ts
- src/app/_mocks/monitors/single.json
- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-348
Monitor details page - more attention is needed to this markup to accommodate _all_ monitor types. Fields not shown here below labels will need to be dynamically loaded depending on the type of monitor.
`npm run test`
> Monitor details page

- src/app/_features/visualize/components/graphs/graphs.component.html
- src/app/_features/visualize/components/graphs/graphs.component.spec.ts
- src/app/_features/visualize/components/graphs/graphs.component.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.html
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
- src/app/_features/visualize/visualize.module.ts
- src/app/_services/visualize/visualize.service.spec.ts
- src/app/_services/visualize/visualize.service.ts
- src/app/app.routing.ts
See ticket here - https://jira.rax.io/browse/MNRVA-370
Beginning the process of adding the visualize view to the app. This is where monitors will be represented in displayed graphs.
`npm run test`
> Visualize Module added

- package-lock.json
- package.json
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.html
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-371
Was created in conjunction with this PR:
https://github.com/racker/Hedwig/pull/58
The goal was to demonstrate a workable technique for downloading, using NPM straight from Github and insuring the project was build.
`npm run start-mock` navigate to `/visualize`
> Add hedwig via github tar + logic for adding graph

- Dockerfile-build
- cloudbuild-deploy.yaml
- nginx.conf
cloudbuild-deploy to build new nginx image with Minerva code
See ticket here - https://jira.rax.io/browse/MNRVA-388
Use cloud builders to compiler angular code and build into an nginx container
gcloud builds submit --config ./cloudbuild-deploy.yaml
n/a
> resolves MNRVA-388

- src/app/_features/visualize/components/selections/selections.component.html
- src/app/_features/visualize/components/selections/selections.component.spec.ts
- src/app/_features/visualize/components/selections/selections.component.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.html
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
- src/app/_features/visualize/visualize.module.ts
- src/app/_services/metrics/metrics.service.spec.ts
- src/app/_services/metrics/metrics.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-373
Created the container page that will orchestrate communication between a user's selections and the graphs being displayed
> Add catch for URL parameters + initial Measurements requests

- cloudbuild.yaml
See ticket here - https://jira.rax.io/browse/MNRVA-398
update cloudbuild.yaml to remove stuff no longer used and run more tests.
> update cloudbuild file

- localenv/config.json
- localenv/config/settings.json
- localenv/routes/metrics.js
- src/app/_features/visualize/components/selections/selections.component.html
- src/app/_features/visualize/components/selections/selections.component.scss
- src/app/_features/visualize/components/selections/selections.component.spec.ts
- src/app/_features/visualize/components/selections/selections.component.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.html
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
- src/app/_mocks/metrics/metrics.service.mock.ts
- src/app/_models/metrics.ts
- src/app/_services/influx/influx.service.spec.ts
- src/app/_services/influx/influx.service.ts
- src/app/_services/metrics/metrics.service.spec.ts
- src/app/_services/metrics/metrics.service.ts
- src/app/_shared/pipes/device-name.pipe.spec.ts
- src/app/_shared/pipes/device-name.pipe.ts
- src/app/_shared/pipes/measurement-name.pipe.spec.ts
- src/app/_shared/pipes/measurement-name.pipe.ts
- src/app/_shared/shared.module.ts
See ticket here - https://jira.rax.io/browse/MNRVA-392
This PR is the ground work for user based selections of systems, measurements, and devices. The page will load a default set of graphs and then behave based on selections.
All updates to the URL are made through the _Container Component_ which then passes on this data to the _Selection Component_ via attributes of the component.
The _Graph Component_ will then load graphs based on the selections being made and/or the URL being loaded.
The _MetricsService_ houses the observables for the selections being made and then reports them to the graph components. 
`npm run test`
> Left column selections foundation + service updates

- localenv/config/settings.json
- localenv/routes/salus.js
- localenv/server.js
- localenv/services/identity/token.js
- src/app/_services/resources/resources.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-408
Add the Salus API for Get Resources & a Resource By ID to the requests coming from the local env. Mainly important for demo'ing and mimicking the portal env.
`npm run tests`
> add Salus API for Resources in localEnv

- localenv/package-lock.json
- localenv/package.json
- localenv/routes/salus.js
- localenv/server.js
- localenv/services/identity/token.js
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/components/list/resourceslist.component.spec.ts
- src/app/_features/resources/components/list/resourceslist.component.ts
- src/app/_features/resources/pages/details/resource-details.page.html
- src/app/_features/resources/pages/details/resource-details.page.spec.ts
- src/app/_features/resources/pages/details/resource-details.page.ts
- src/app/_mocks/resources/resources.service.mock.ts
- src/app/_mocks/resources/single.json
- src/app/_models/resources.ts
- src/app/_services/resources/resources.service.spec.ts
- src/app/_services/resources/resources.service.ts
- src/app/_shared/_components/pagination/pagination.component.html
- src/app/_shared/_components/pagination/pagination.component.spec.ts
- src/app/_shared/_components/pagination/pagination.component.ts
- src/environments/environment.mock.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
See ticket here - https://jira.rax.io/browse/MNRVA-416
- Connected requests to the API for a single resource for local environment
- Added Interfaces for structure of a Resource & a collection of Resources
`npm run test`
> Single resource MNRVA 416

- localenv/routes/salus.js
- src/app/_features/resources/pages/details/resource-details.page.html
- src/app/_features/resources/pages/details/resource-details.page.scss
- src/app/_features/resources/pages/details/resource-details.page.spec.ts
- src/app/_features/resources/pages/details/resource-details.page.ts
- src/app/_models/resources.ts
- src/app/_services/resources/resources.service.spec.ts
- src/app/_services/resources/resources.service.ts
- src/app/_shared/_components/add-fields/add-fields.component.html
- src/app/_shared/_components/add-fields/add-fields.component.scss
- src/app/_shared/_components/add-fields/add-fields.component.spec.ts
- src/app/_shared/_components/add-fields/add-fields.component.ts
- src/app/_shared/shared.module.ts
- src/app/_shared/validators/disallow.validator.spec.ts
- src/app/_shared/validators/disallow.validator.ts
- src/app/_shared/validators/keyvalue.validator.spec.ts
- src/app/_shared/validators/keyvalue.validator.ts
- src/app/app.component.scss
- src/environments/environment.mock.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
See ticket here - https://jira.rax.io/browse/MNRVA-337
Delete a resource from resource detail view
`npm run test`
> Delete a resource 

- angular.json
- package-lock.json
- package.json
- src/index.html
- src/main.ts
See ticket here - https://jira.rax.io/browse/MNRVA-419
Update the version of Helix - it now is bundled with webcomponents so we ripped out the project's references as not to conflict
`npm run test`
> update Helix -> .018.0-rc.2

- localenv/api.js
- localenv/routes/monitors.js
- localenv/routes/resources.js
- src/app/_features/monitors/components/list/monitorslist.component.html
- src/app/_features/monitors/components/list/monitorslist.component.spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.ts
- src/app/_mocks/monitors/collection.json
- src/app/_models/monitors.ts
- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-205
Retrieves a list of monitors
_Once the Salus API is updated to account for monitor names being defaulted this feature will need an update_
`npm run test`
> Monitors list

- localenv/api.js
- localenv/routes/monitors.js
- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/monitors/pages/details/monitor-details.page.scss
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-215
Delete a single monitor from the detailed monitor page
`npm run test`
> Delete single monitor functionality

- localenv/package-lock.json
- localenv/package.json
- package-lock.json
- package.json
N/A - Hotfix
The project was experiencing build errors due to a mismatch in some of the compiler packages and Typescript. Angular version bumped up to _7.2.0_. Also addressed some security vulnerabilities in the _localenv_ packages.
`npm run test`
> angular/compiler & cli build fixes + localenv

- src/app/_services/logging/logging.service.spec.ts
- src/app/_services/logging/logging.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-432
An observable property added and unit test added for the same
npm run test
> Observable added  for Alert message

- src/app/_services/error.service.spec.ts
- src/app/_services/error.service.ts
- src/app/_services/monitors/schema.service.ts
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-421
Error type of alert in case error in request/response  
npm run test
> Alert message mnrva 421

- src/app/_features/monitors/config/disk.ts
- src/app/_features/monitors/config/index.ts
See ticket here - https://jira.rax.io/browse/MNRVA-423
Disk monitor type populates with appropriate field and validators
> Disk Monitor support added

- src/app/_features/monitors/config/index.ts
- src/app/_features/monitors/config/mem.ts
See ticket here - https://jira.rax.io/browse/MNRVA-357
Mem type monitor config file added
> mem config file added

- src/app/_features/monitors/config/index.ts
- src/app/_features/monitors/config/net.ts
See ticket here - https://jira.rax.io/browse/MNRVA-358
network monitor config file added.
npm run test
> Net monitor mnrva 358

- src/app/_features/monitors/pages/details/monitor-details.page.html
See ticket here - https://jira.rax.io/browse/MNRVA-446
showing the list of labels vertically in key value pair
npm run test
> Label monitor mnrva 446

- src/index.html
See ticket here - https://jira.rax.io/browse/MNRVA-453
Horizontal menu items
npm run test
> Horizontal navigation bar

- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_mocks/resources/collection.json
- src/app/_services/monitors/monitor.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-465
Added plugin details for a monitor to monitor details page - also updated resource mocks
> Plugin details added + resource mock fix

- localenv/api.js
- localenv/routes/zones.js
- src/app/_mocks/zones/zone.service.mock.ts
- src/app/_mocks/zones/zones.json
- src/app/_models/zone.ts
- src/app/_services/zones/zone.service.spec.ts
- src/app/_services/zones/zones.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-458
Get  monitor zones corresponding to tenant id
npm run test, npm run mock-start
http://dev.i.rax.io:3001/api/salus/zones
> Monitor zon scrvc 458

- package-lock.json
- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_mocks/monitors/single.json
- src/app/app.module.ts
See ticket here - https://jira.rax.io/browse/MNRVA-466
Added support to display:
- resourceId
- excludedResourceIds
- labelSelectorMethod
- policy
`npm run test`
> Additional settings show + hide

- src/app/_features/monitors/mon.utils.ts
- src/app/_features/monitors/pages/create/monitor-create.page.spec.ts
- src/app/_features/monitors/pages/create/monitor-create.page.ts
- src/styles.scss
See ticket here - https://jira.rax.io/browse/MNRVA-454
1.  Min and Max validation added for numeric fields.
2.  Enum for attributes.
npm run start-mock
> min, max validation, enum for Attributes added

- e2e/src/specs/ListOfMonitor.e2e-spec.ts
- e2e/src/specs/pagination.e2e-spec.ts
- src/app/_shared/components/pagination/pagination.component.html
See ticket here - https://jira.rax.io/browse/MNRVA-463
Pagination Test:- 
✓ Should check if last page button is navigating
✓ Should check if first-page button is navigating
✓ Should check if next page button is navigating
✓ Should check if previous page button is navigating
✓ Should Populate first page
✓ Should Populate second page
✓ Should Populate third page
✓ Should check if first-page button is disabled on initial load
✓ should check if previous page button is disabled on initial load
✓ should check if last page button is enabled on initial load
✓ should check if the next page button is enabled on initial load
npm run e2e
> Pagination test 463

- src/app/_features/monitors/pages/create/monitor-create.page.ts
- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_models/monitors.ts
- src/app/_shared/components/add-fields/add-fields.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-517
Update label selector from Monitor details page
`npm run test`
> Update monitor label selectors

- e2e/src/commons/navigations.ts
- e2e/src/specs/BreadTest.e2e-spec.ts
- e2e/src/specs/CreateMonitor_cpu.e2e-spec.ts
- e2e/src/specs/InitialError.e2e-spec.ts
- e2e/src/specs/MonitorDetailsDeleteAction.e2e-spec.ts
- e2e/src/specs/labels_resources.e2e-spec.ts
- e2e/src/specs/pagination.e2e-spec.ts
- e2e/src/specs/portTest.e2e-spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-484
https://jira.rax.io/browse/MNRVA-493
✓ Should check that the user can delete the monitor detail
✓ Should check the editing of a Monitor name is updated
npm run e2e
> Test update monitor name 484

- src/app/_features/monitors/components/dynamic-form/dynamic-form.component.html
- src/app/_features/monitors/components/dynamic-form/dynamic-form.component.spec.ts
- src/app/_features/monitors/components/dynamic-form/dynamic-form.component.ts
- src/app/_features/monitors/interfaces/field.interface.ts
- src/app/_features/monitors/monitors.module.ts
- src/app/_features/monitors/pages/create/monitor-create.page.spec.ts
- src/app/_features/monitors/pages/create/monitor-create.page.ts
- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_models/monitors.ts
- src/app/_shared/components/add-fields/add-fields.component.html
See ticket here - https://jira.rax.io/browse/MNRVA-518
Support added for remote type monitors. 
- Create Monitor Page
- Monitor Details Page
`npm run test`
Create a remote type monitor
View a remote type monitor & update
> Support for monitoring zones

- localenv/api.js
- localenv/routes/resources-search.js
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/components/list/resourceslist.component.spec.ts
- src/app/_features/resources/components/list/resourceslist.component.ts
- src/app/_features/resources/components/search/search.component.html
- src/app/_features/resources/components/search/search.component.spec.ts
- src/app/_features/resources/components/search/search.component.ts
- src/app/_features/resources/resources.module.ts
- src/app/_services/resources/resources.service.spec.ts
- src/app/_services/resources/resources.service.ts
- src/app/_shared/utils.ts
See ticket here - https://jira.rax.io/browse/MNRVA-522
Search Resources
1. Navigate to Resources list `/resources`
2. Begin typing, the results will update after entering 2 characters
> Search resources mnrva 522

- e2e/protractor.conf.js
- e2e/src/features/monitoring/monitorlist/ListOfMonitor.e2e-spec.ts
- e2e/src/features/monitoring/monitorlist/monitorsPagination.e2e-spec.ts
- e2e/src/pages/monitorlistpage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-510
Added 13 MonitorPagination testcases as part of MNRVA-510 testing
npm run e2e
> Adding monitorsPagination testcases

- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_mocks/monitors/single.json
See ticket here - https://jira.rax.io/browse/MNRVA-527
Change ISO Time duration format in seconds
Updated one 
Old
> Iso conversion mnrva 527

- localenv/api.js
- localenv/routes/event-task.js
See ticket here - https://jira.rax.io/browse/MNRVA-541
A node js Route service added  for the Create Event.
1.run with localenv 
2. curl post http://dev.i.rax.io:3001/api/salus/event-tasks
with json body 
{
"measurement": "cpu",
"name": "cpu",
"taskParameters": {
"labelSelector": {
"agent_environment": "localdev"
},
"criticalStateDuration": 2,
"warningStateDuration": null,
"infoStateDuration": null,
"stateExpressions": [
{
"state": "CRITICAL",
"message": "critical threshold was hit",
"expression": {
"type": "comparison",
"comparator": "<",
"metricName": "total_cpu",
"comparisonValue": 3
}
}
]
}
}
> Event service mnrva 541

- e2e/protractor.conf.js
- e2e/src/features/resources/resourcedetails/deleteResource.e2e-spec.ts
- e2e/src/pages/resourcelistpage.ts
- e2e/src/pages/resourcesdetailspage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-494
Automated "MNRVA-494:Resource details delete Resource" testcases.
> Delete resource mnrva 494

- e2e/protractor.conf.js
- e2e/src/features/resources/resourcedetails/AddRemoveMetaData.e2e-spec.ts
- e2e/src/overlays/metadataOverlay.ts
- e2e/src/pages/resourcesdetailspage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-509
Automated testcases of MNRVA-509
1.Navigate to resource details page
2.Initiate metadata popover
3.Add or remove fields set
> Adding testcases of MNRVA-509

- package-lock.json
- package.json
- src/app/_features/events/config/measurements.json
See ticket here - https://jira.rax.io/browse/MNRVA-551
This is a collection of valid measurements for creating events.
> Event measurements mnrva 551

- e2e/src/features/monitoring/monitordetails/updateDynamicPluginData.e2e-spec.ts
- e2e/src/overlays/updateplugindataOverlay.ts
- e2e/src/pages/monitordetailspage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-507
update the dynamic plugin data of any monitor using the dynamic form component.
> Adding testacses of MNRVA-507

- src/app/_features/events/components/event-details/event-details.component.html
- src/app/_features/events/components/event-details/event-details.component.scss
- src/app/_features/events/components/event-details/event-details.component.spec.ts
- src/app/_features/events/components/event-details/event-details.component.ts
- src/app/_features/events/events.module.ts
- src/app/_mocks/events/getAllEvents.json
See ticket here - https://jira.rax.io/browse/MNRVA-552
Add the expression section of the event to the details page
- Navigate to the admin link in the nav bar
- Click on a monitor
- Navigate to the events section of the page and click an event
- There is a section titled **Expressions** here are the related expressions for this event.
> Event expression mnrva 552

- src/app/_features/events/components/list/eventslist.component.html
- src/app/_features/events/events.module.ts
See ticket here - https://jira.rax.io/browse/MNRVA-570
Create-event route renamed.
> Bug mnrva 570

- localenv/routes/event-task.js
- projects/admin/src/app/tab/_features/monitors/pages/details/details.component.html
- projects/admin/src/app/tab/_features/monitors/pages/details/details.component.ts
- projects/admin/src/app/tab/_features/resources/pages/details/admin-resource-details.page.html
- projects/admin/src/app/tab/_features/resources/pages/details/admin-resource-details.page.ts
- src/app/_features/events/components/list/eventslist.component.html
- src/app/_features/events/components/list/eventslist.component.ts
- src/app/_features/events/events.module.ts
- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_features/resources/pages/details/resource-details.page.html
- src/app/_features/resources/pages/details/resource-details.page.ts
- src/app/_services/events/events.service.ts
- src/app/_shared/components/modal/modal.component.html
- src/app/_shared/components/modal/modal.component.spec.ts
- src/app/_shared/components/modal/modal.component.ts
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-567
1) Replace <hx-modal> with new common component <app-modal> and added every where.
2) create functionality to pass header, message according to your choice in <app-modal> tag.
3) Complete delete event functionality with common modal.
**Testing:**
> Update modals mnrva 567

- Dockerfile
- cloudbuild.yaml
- package-lock.json
- package.json
See ticket here - https://jira.rax.io/browse/MNRVA-564
Update ubuntu image in GCP cloud registry & update protractor version.
Works on any push
> Update Ubunutu image in gcp + remove build step

- e2e/src/features/admin/displayEventDetails.e2e-spec.ts
- e2e/src/pages/eventDetailsPage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-574
As a team we're wanting write a test ensures the State Expression section of an event has loaded.
AC: A test that runs for state expression
> Test event details mnrva 574

- e2e/src/features/monitoring/monitordetails/deleteEvent.e2e-spec.ts
- e2e/src/overlays/deleteEventOverlay.ts
- e2e/src/pages/monitorDetailsPage.ts
- src/app/_features/events/components/list/eventslist.component.html
- src/app/_shared/components/modal/modal.component.html
See ticket here - https://jira.rax.io/browse/MNRVA-575
As a team we're wanting an e2e test that verifies that an event can be deleted.
AC: a test that checks whether an event can be deleted.
> Delete event mnrva 575

- angular.json
- projects/admin/src/app/tab/_features/events/event-details/event-details.component.spec.ts
- projects/admin/src/app/tab/_features/resources/pages/details/admin-resource-details.page.spec.ts
- projects/admin/src/app/tab/_features/resources/pages/details/admin-resource-details.page.ts
See ticket here - https://jira.rax.io/browse/MNRVA-571
Test cases added for Admin resource details page
ng test --project=admin
> Admin resource details mnrva 571

- src/app/_features/monitors/components/list/monitorslist.component.html
- src/app/_features/monitors/components/list/monitorslist.component.scss
- src/app/_features/monitors/components/list/monitorslist.component.spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.ts
- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-230
1) Create new modal for showing success message If monitor is deleted and error if 404 and other issue occurred during deleting monitor.
Use promiseAll for deleting multiple monitors and check which one failed and which on being succeeded.
**Testing:**
`
npm run test:unit`
> Delete multiple monitor mnrva 230

- e2e/src/features/monitoring/monitorlist/deleteMultipleMonitors.e2e-spec.ts
- e2e/src/features/resources/resourceslist/listOfResources.e2e-spec.ts
- e2e/src/overlays/deleteSelectedMonitorOverlay.ts
- e2e/src/pages/monitorListPage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-583
Have added testcases of Delete Multiple Monitors-MNRVA-583 story.
Note:When running the regression suite you might come across few failures.Please ignore those as they are run time issues.
> Adding testcases of DeleteMultipleMonitors-MNRVA-583

- projects/admin/src/app/tab/_features/monitors/pages/details/details.component.spec.ts
- src/app/_features/events/components/event-details/event-details.component.spec.ts
- src/app/_features/monitors/components/input/input.component.spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.ts
- src/app/_features/monitors/components/monitor-search/monitor-search.component.spec.ts
- src/app/_features/monitors/components/resource_list/resource-list.component.spec.ts
- src/app/_features/monitors/components/resource_list/resource-list.component.ts
- src/app/_features/monitors/pages/create/monitor-create.page.spec.ts
- src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
- src/app/_features/monitors/pages/monitors/monitors.page.spec.ts
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/components/monitor_list/monitor-list.component.spec.ts
- src/app/_features/resources/components/search/search.component.spec.ts
- src/app/_features/resources/pages/details/resource-details.page.spec.ts
- src/app/_interceptors/mock-resources.interceptor.ts
- src/app/_interceptors/server-error.interceptor.ts
- src/app/_mocks/monitors/collection.json
- src/app/_mocks/monitors/monitors.service.mock.ts
- src/app/_mocks/resources/resources.service.mock.ts
- src/app/_services/events/events.service.spec.ts
- src/app/_services/logging/logging.service.spec.ts
- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
- src/app/_shared/components/breadcrumb/breadcrumb.component.spec.ts
- src/app/_shared/components/modal/modal.component.spec.ts
- src/app/_shared/utils.spec.ts
- src/app/_shared/validators/disallow.validator.spec.ts
- src/app/app.component.spec.ts
See ticket here - https://jira.rax.io/browse/MNRVA-587
@RiaRenold we need a manual test each monitoring feature  for both env: Mock, prod
1. Updated the monitor mock service to handle all requests.
> Refactor monitoring services 587

- src/app/_features/monitors/components/list/monitorslist.component.html
- src/app/_features/monitors/components/list/monitorslist.component.spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-592
Fixed bugs.
Add test cases for functions.
**Testing:**
> Bug mnrva 592

- e2e/src/features/monitoring/monitordetails/deleteEvent.e2e-spec.ts
- e2e/src/features/monitoring/monitorlist/deleteMultipleMonitors.e2e-spec.ts
- e2e/src/features/resources/resourceslist/deleteMultipleResources.e2e-spec.ts
- e2e/src/overlays/deleteEventOverlay.ts
- e2e/src/overlays/deleteSelectedMonitorOverlay.ts
- e2e/src/overlays/deleteSelectedResourceOverlay.ts
- e2e/src/pages/monitorListPage.ts
- e2e/src/pages/resourcelistpage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-584
-Added testcases as part of Delete Multiple Resources functionality(MNRVA-584).
-made some minor changes in the testcases of Delete Multiple Monitors story(MNRVA-583).
> Delete multiple resources mnrva 584

- src/app/_services/featureConfig/featureConfig.service.spec.ts
- src/app/_services/featureConfig/featureConfig.service.ts
- src/app/_services/labels/label.service.spec.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/environments/environment.mock.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/index.html
See ticket here - https://jira.rax.io/browse/MNRVA-340
1. Feature flag property added in Envs.
2. Accessing Envs using FeatureFlagging service.
> feat: 340 Feature flagging

- src/app/_features/monitors/components/list/monitorslist.component.spec.ts
- src/app/_features/monitors/components/list/monitorslist.component.ts
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/components/list/resourceslist.component.scss
- src/app/_features/resources/components/list/resourceslist.component.spec.ts
- src/app/_features/resources/components/list/resourceslist.component.ts
- src/app/_models/monitors.ts
- src/app/_models/resources.ts
- src/app/app.routing.ts
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-593
Selecting delete all resources checkbox and deleting will refresh the list and clear the checkbox
**Testing:**
`npm run testunit`
**NOTE:-** Already taken latest pull from level but still it is going to admin section by default. so would be fixed once I merge this branch to level.
> Multiple deletion for Resources + delete all

- localenv/routes/resources.js
- src/app/_features/monitors/components/additional-settings/additional-settings.component.ts
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/components/list/resourceslist.component.scss
- src/app/_features/resources/components/list/resourceslist.component.spec.ts
- src/app/_features/resources/components/list/resourceslist.component.ts
- src/app/_mocks/resources/resources.service.mock.ts
- src/app/_mocks/resources/testResource.json
- src/app/_services/resources/resources.service.ts
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-608
Resources page has the ability to sort.
Added sorting by resource id.
**Testing:**
> Sorting Resources

- e2e/src/features/monitoring/monitorlist/listOfMonitor.e2e-spec.ts
- e2e/src/features/monitoring/monitorlist/monitorsPagination.e2e-spec.ts
- e2e/src/features/monitoring/monitorlist/monitorsPaginationenabledisable.e2e-spec.ts
See ticket here - https://jira.rax.io/browse/MNRVA-625
- Changed the xpath in the listOfMonitor.e2e-spec.ts test case
- Divided the test case - monitorsPagination.e2e-spec.ts into two and created a new test case - monitorsPaginationenabledisable.e2e-spec.ts
> e2etestfix

- .gitignore
- src/app/_features/monitors/components/list/monitorslist.component.html
- src/app/_features/monitors/components/list/monitorslist.component.ts
- src/app/_features/monitors/components/resource_list/resource-list.component.html
- src/app/_features/resources/components/list/resourceslist.component.html
- src/app/_features/resources/components/monitor_list/monitor-list.component.html
- src/app/_shared/components/zero-results/zero-results.component.html
- src/app/_shared/components/zero-results/zero-results.component.scss
- src/app/_shared/components/zero-results/zero-results.component.spec.ts
- src/app/_shared/components/zero-results/zero-results.component.ts
- src/app/_shared/shared.module.ts
- src/styles.scss
See ticket here - https://jira.rax.io/browse/MNRVA-611
Zero results message for Monitors. New shared components to be used in multiple instances of a results set not having 
Create zero results for monitors & total monitors
> Zero monitors mnrva 611

- .gitignore
- helpers/setup.js
- proxy.stage.conf.js
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-639
1) Setup Referrer Header for local API proxy.
**Testing:**
`npm run start:unit`
> Create Referer header for local API Proxy

- e2e/src/features/misc/BreadTest.e2e-spec.ts
- e2e/src/features/misc/InitialError.e2e-spec.ts
- e2e/src/features/misc/pagination.e2e-spec.ts
- e2e/src/features/misc/spinnertest.e2e-spec.ts
- e2e/src/features/monitoring/monitordetails/deleteEvent.e2e-spec.ts
- e2e/src/pages/app.po.ts
- e2e/src/pages/monitorListPage.ts
See ticket here - https://jira.rax.io/browse/MNRVA-624
1) Refactored all the test cases under the misc folder
2) Mentioned all the locators in the app.po.ts and monitorListPage.ts
> Refactoringofmisc

- src/app/_features/monitors/pages/details/monitor-details.page.ts
- src/app/_services/labels/label.service.ts
- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-638
-> Fixed error coming on staging env for particular api's related to monitoring and resources section. 
**Testing:**
> Update Services for Portal Env

- src/app/_services/resources/resources.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-684
Fixed Resource  pagination 
> Pagination mnrva 684

- src/app/_features/monitors/pages/details/monitor-details.page.ts
See ticket here - https://jira.rax.io/browse/MNRVA-167
Bug fix, monitor name update failure
- Navigate to a monitor's detail page
- Click pencil next to the title of the monitor
- Enter non alpha numeric characters e.g. '&&&&'
- When the update fails spinner will be removed
> Monitor spinner mnrva 167

- e2e/src/features/resources/resourceslist/resourcesPagination.e2e-spec.ts
See ticket here - https://jira.rax.io/browse/MNRVA-687
I have placed the resourcesPagination.e2e-spec file under the resourcelist folder in order to follow the POM design
> replaced the pagination file

- src/app/_features/monitors/pages/details/monitor-details.page.html
- src/app/_features/resources/pages/details/resource-details.page.html
See ticket here - https://jira.rax.io/browse/MNRVA-683
Fix actions links:
- Resources detail (label, metadata) 
- Monitor detail (label, settings, rename monitor)
Navigate to Resources/Monitor detail page
Select Actions
Click any of the edit links
> update action menu items for popovers

- src/app/_services/monitors/monitor.service.spec.ts
- src/app/_services/monitors/monitor.service.ts
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-702
Fixed **"Media type not supported issue with status 415"** and **"Failed to parse JSON"** error.
**Testing:**
> Getting an error message on updating Monitors name or Additional settings

- e2e/src/features/monitoring/monitorlist/listOfMonitor.e2e-spec.ts
- e2e/src/features/resources/resourceslist/listOfResources.e2e-spec.ts
- env/environment.ts
- src/app/_features/monitors/components/list/monitorslist.component.html
See ticket here - https://jira.rax.io/browse/MNRVA-679
- Remove Suppression & Copy monitor functionality
- Remove e2e tests for this functionality
- Stop webdriver from updating it's chromedriver version
> remove e2e tests for removed buttons

- cloudbuild-deploy.yaml
**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-449
1) Add rule for deploying compodoc static page documentation to new bucket which is publicly accessible over the internet.
2) Add link to the repo inside README.md
**Testing:**
**Screenshots:**
> Compodoc Static Page

- app-admin-prod.yaml
- app-admin-staging.yaml
- cloudbuild-admin-deploy.yaml
- cloudbuild-admin.yaml
- cloudbuild-deploy.yaml
- package.json
- projects/admin/src/app/app.component.spec.ts
See ticket here - https://jira.rax.io/browse/MNRVA-735
Admin UI build, test & deployment to GCP App Engine. New triggers added:
- Minerva-Admin-Build-Test
- Minerva-Admin-Deploy-Staging
- Minerva-Admin-Deploy-Production
> Admin deploy mnrva 735

- src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-788
Test cases added for dropdown loading and queryparams changes
> Test cases for left mnrva 788

- projects/admin/README.md
- src/app/_features/visualize/components/graphs/graphs.component.html
- src/app/_features/visualize/components/graphs/graphs.component.spec.ts
- src/app/_features/visualize/components/graphs/graphs.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-191
Add README for admin project - updates to graph .component as it was failing its test. 
> add README admin project + update graphs.component pass test

- cloudbuild.yaml
- package-lock.json
- package.json
- projects/admin/src/app/dashboard/_features/monitors/monitorDetails.component.spec.ts
- src/app/_features/visualize/components/selectNav/metric-group/metric-dropdown.component.html
- src/app/_features/visualize/components/selectNav/metric-group/metric-dropdown.component.spec.ts
- src/app/_features/visualize/components/selectNav/metric-group/metric-dropdown.component.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.html
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
- src/app/_features/visualize/visualize.module.ts
- src/app/_mocks/metrics/metrics.json
- src/app/_mocks/metrics/metrics.service.mock.ts
- src/app/_services/metrics/metrics.service.ts
See ticket here - https://jira.rax.io/browse/MNRVA-786
1. Tag dropdown added to left nav
2.  Test cases and changed
> Selection tags mnrva 786

- dev/Insomnia-workspace.yaml
See ticket here - https://jira.rax.io/browse/MNRVA-XXXX
> Insomina mnrva 793

- e2e/protractor.conf.js
- e2e/src/features/visualize/visualizeview/timeRange.e2e-spec.ts
- e2e/src/pages/visualizeViewPage.ts
> Visualize Time Range

- package-lock.json
- package.json
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.html
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.scss
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
- src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts
- src/app/_mocks/metrics/metrics.json
- src/app/_shared/components/hedwig-graph/hedwig-graph.component.html
- src/app/_shared/components/hedwig-graph/hedwig-graph.component.scss
- src/app/_shared/components/hedwig-graph/hedwig-graph.component.spec.ts
- src/app/_shared/components/hedwig-graph/hedwig-graph.component.ts
See ticket here - https://jira.rax.io/browse/MNRVA-178
Graph grid and table with resizing
> Graph grid mnrva 178
