racker/Minerva

gulpfile.js
package.json
tasks/sample.js

**JIRA**: https://jira.rax.io/browse/MNRVA-7
**Description**: 
Sets up gulp as our task runner of choice. Notice that each individual task will be broken down into individual files located in the tasks folder. This will help combat long running gulpfiles. I have provided a sample task to show how that pipes through.
**Testing**: 
Simply run `gulp` and it will execute the default task.

Configures initial setup for gulp

---

.gitignore
angular.json
e2e/src/app.e2e-spec.ts
e2e/src/app.po.ts
package-lock.json
package.json
src/app/app.component.html
src/app/app.module.ts
src/index.html

**JIRA**: https://jira.rax.io/browse/MNRVA-8
**Description**:
Sets up Helix-UI to bootstrap our HTML elements.  Because of the current state of Helix, we are unable to fully componentize Helix at this point (IE: navigation and content areas)
Also brought in http-server to serve up the dist folder, which is a better representation of the deployed application.
**Test**:
Run `npm start` and view the magic that is Helix
Run `npm run e2e` and watch the console output
**Screenshot**:

Configures Helix-UI as our bootstrapping library

---

package-lock.json
package.json
src/app/poc-data-call/poc-data-call.component.html
src/app/poc-data-call/poc-data-call.component.ts

**JIRA**: https://jira.rax.io/browse/MNRVA-21
**Description**:
Uses d3.js to visualize live metrics v2 data.  This graph is a POC and is throw away. Do not pay attention to graph labels as I didn't want to spend too much time flushing that out since it is throw away anyways.  There is also no automated testing for this by design
**Test**:
Run `ng serve` and view the graph
**Screenshot**

Adds a POC graph for live metrics data

---

src/app/app.module.mock.ts
src/app/app.module.ts
src/app/poc-api-call.service.mock.ts
src/app/portal-data.service.spec.ts
src/app/portal-data.service.ts
src/index.html

See ticket here - https://jira.rax.io/browse/MNRVA-31
Turns out that pilot will be injected for us by the portal platform. It will use `<pilot-nav></pilot-nav>` as the selector. So all we really need to do is just have that on the index page. Locally we won't need to have pilot there so we will be good to go.  Also portal provides an object with account specifics, `Window['PORTAL_DATA']`
Only the to test here is the portal data service.  Run `npm test` to see the tests run.

Adds pilot nav element and PORTAL_DATA service

---

src/app/app.module.ts
src/app/log-levels.enum.ts
src/app/logging.service.spec.ts
src/app/logging.service.ts
src/app/poc-data-call/poc-data-call.component.ts

See ticket here - https://jira.rax.io/browse/MNRVA-28
Turns out that WinstonJs does not support in browser logging. It is meant for back end node applications. It was easy enough to just create a logging service to meet our needs.
Run the application `npm start`
Then play around with setting the `LOG_LEVEL` in local storage.
Observe expected behavior in the console.

Adds a logging service

---

README.md
angular.json
package.json

See ticket here - https://jira.rax.io/browse/MNRVA-130
Adds a proxy for local development so that we can point the browser to `dev.i.rax.io:4200`.  This should allow for the ability to login to the application locally and have ADFS point to our local application.
Follow the proxy setup instructions on the readme file
run `npm start` and navigate to `dev.i.rax.io`

sets up proxy to dev.i.rax.io

---

src/app/_interceptors/server-error.interceptor.ts
src/app/_services/error.service.spec.ts
src/app/_services/error.service.ts
src/app/_shared/global-error.handler.ts
src/app/_shared/shared.module.ts

See ticket here - https://jira.rax.io/browse/MNRVA-321
Add global error handler that implements the logging service. This will be great for one stop shop to send all app errors to a server/db in the future.
`npm run test`

add global error handler + server error interceptor

---

src/app/_features/resources/components/list/resourceslist.component.html
src/app/_features/resources/components/list/resourceslist.component.spec.ts
src/app/_features/resources/components/list/resourceslist.component.ts

See ticket here - https://jira.rax.io/browse/MNRVA-312
Checkbox column now checks or unchecks all resources in grid. 
Checking at least one allows for the actions of the top buttons
`npm run test`
Check one checkbox, all action buttons should disable
Check top checkbox column and all others in the column should check

Hide show button logic resourcelist

---

package.json
src/app/_features/monitors/monitors.module.ts
src/app/_features/monitors/pages/monitors/monitors.page.html
src/app/_features/monitors/pages/monitors/monitors.page.spec.ts
src/app/_features/monitors/pages/monitors/monitors.page.ts
src/app/app.routing.ts

See ticket here - https://jira.rax.io/browse/MNRVA-341
Introduces the Monitors module and accompanying pages
`npm run test` or navigate to `http://dev.i.rax.io:(4200 || 3000)/intelligence/monitors`

Add monitors module + pages structure

---

localenv/package-lock.json
localenv/package.json
localenv/routes/salus.js
localenv/server.js
localenv/services/identity/token.js
src/app/_features/resources/components/list/resourceslist.component.html
src/app/_features/resources/components/list/resourceslist.component.spec.ts
src/app/_features/resources/components/list/resourceslist.component.ts
src/app/_services/resources/resources.service.spec.ts
src/app/_services/resources/resources.service.ts
src/app/_shared/_components/pagination/pagination.component.html
src/app/_shared/_components/pagination/pagination.component.spec.ts
src/app/_shared/_components/pagination/pagination.component.ts
src/environments/environment.mock.ts
src/environments/environment.prod.ts
src/environments/environment.ts

See ticket here - https://jira.rax.io/browse/MNRVA-405
Portal had requested that we make the API endpoints absolute instead of relative as this was messing up the requests (_./environments/environment.ts_).
Tested and connected Salus - Resource API for Prod environment and adjusted the pagination and count to reflect the API accurately.
This then made it necessary to update the pagination component & tests as I was not previously using a base zero for the paging.
`npm run test`
**Live data from Salus Prod!**

update API environment endpoints + adjusted collections Resources API 

---

localenv/routes/salus.js
src/app/_features/resources/pages/details/resource-details.page.html
src/app/_features/resources/pages/details/resource-details.page.scss
src/app/_features/resources/pages/details/resource-details.page.spec.ts
src/app/_features/resources/pages/details/resource-details.page.ts
src/app/_models/resources.ts
src/app/_services/resources/resources.service.spec.ts
src/app/_services/resources/resources.service.ts
src/app/_shared/_components/add-fields/add-fields.component.html
src/app/_shared/_components/add-fields/add-fields.component.scss
src/app/_shared/_components/add-fields/add-fields.component.spec.ts
src/app/_shared/_components/add-fields/add-fields.component.ts
src/app/_shared/shared.module.ts
src/app/_shared/validators/disallow.validator.spec.ts
src/app/_shared/validators/disallow.validator.ts
src/app/_shared/validators/keyvalue.validator.spec.ts
src/app/_shared/validators/keyvalue.validator.ts
src/app/app.component.scss
src/environments/environment.mock.ts
src/environments/environment.prod.ts
src/environments/environment.ts

See ticket here - https://jira.rax.io/browse/MNRVA-417
Update Resource with Labels and Metadata. 
- Created a shared reusable component `add-fields.component`
- Added two new validators to shared module and used by `add-fields.component`
_NOTE_: There's an unexpected behavior with the Helix popover `<hx-popover>` it closes automatically when changes happen within the DOM and synthetic click events happen within the body of the popover. The Helix team is aware of this and haven't yet come to a solution, but have proposed workarounds. I think there's a workaround solution but I would need the time to go in deeper. 
Valdiation: 
- Cannot submit a key without a value
- Cannot submit a value without a key
- Labels - cannot use _agent_ in the key field
This is covered in great detail here: …

Update Resource + Field Validators

---

localenv/routes/monitors.js
package-lock.json
package.json
src/app/_features/monitors/pages/details/monitor-details.page.html
src/app/_features/monitors/pages/details/monitor-details.page.spec.ts
src/app/_features/monitors/pages/details/monitor-details.page.ts
src/app/_mocks/monitors/single.json
src/app/_models/monitors.ts
src/app/_services/monitors/monitor.service.spec.ts
src/app/_services/monitors/monitor.service.ts
src/app/_shared/pipes/duration-seconds.pipe.spec.ts
src/app/_shared/pipes/duration-seconds.pipe.ts
src/app/_shared/shared.module.ts

See ticket here - https://jira.rax.io/browse/MNRVA-264
Addition of monitor details - there will need to be a revisited focus on the _plugin_ details for each monitor plugin type when creating the update feature
`npm run test`

Monitor details read-only

---

projects/admin/src/app/_features/resources/pages/details/admin-resource-details.page.html
projects/admin/src/app/_features/resources/pages/details/admin-resource-details.page.scss
projects/admin/src/app/_features/resources/pages/details/admin-resource-details.page.spec.ts
projects/admin/src/app/_features/resources/pages/details/admin-resource-details.page.ts
projects/admin/src/app/tab/tabset-routing.module.ts
projects/admin/src/app/tab/tabset.module.ts
src/app/_features/resources/components/list/resourceslist.component.html
src/app/_features/resources/components/list/resourceslist.component.ts
src/app/_features/resources/resources.module.ts

**JIRA:**
See ticket here - [](https://jira.rax.io/browse/MNRVA-536)
1) Created separate component of resource details page inside admin panel.
2) Add routing URL inside tab-set module.
3) Add flag to check if URL is coming from admin or not.
4) Redirect user/customer from resource list on the basis of flag (admin or not).
**Testing:**
`npm run test`
**Screenshots:**

Resource details page mnrva 536

---

e2e/src/features/monitoring/createmonitor/createNetworkMonitor.e2e-spec.ts

See ticket here - https://jira.rax.io/browse/MNRVA-502
-As a user Navigate to monitoring
-Click on Create monitor button.
-Select monitor type "Mem", fill the required data, and click on submit after monitor creation it must navigate to monitoring and new monitor should listed in the monitor grid.

Modified test summary in describe block

---

README.md
makefile
package.json
projects/admin/src/app/app.module.ts

**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-565
1) Create makefile - a file which is used for creating multiple builds using make inbuilt automation tool in CLI
2) create two build folders with name Minerva and Admin inside Dist folder.
**Testing:**

Create a way to separate the Admin build from Minerva

---

src/app/_features/monitors/mon.utils.spec.ts
src/app/_features/monitors/mon.utils.ts
src/app/_features/resources/components/monitor_list/monitor-list.component.html

**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-562
1. Remove function which is broken as summary obj is not coming in api call.
2. As per discussion, only monitorType is a field which can be used in place of monitorName when the same is empty in some cases.
**Testing:**

Maximum call stack size exceeded.

---

e2e/src/features/admin/adminLayout.e2e-spec.ts
e2e/src/pages/adminToolsPage.ts

See ticket here - https://jira.rax.io/browse/MNRVA-506
As a team, we'd like the /admin section of Minerva to have the general layout of monitoring.rackspace.net
AC: Search box and tabs are viewable in the admin section
1.Navigate to Admin
2.there should be the search box, monitor, and resource tab.

Admin layout mnrva 506

---

angular.json
package.json
projects/admin/src/app/tab/tabset.module.ts
src/app/_features/monitors/components/resource_list/resource-list.component.spec.ts
src/app/_features/monitors/mon.utils.spec.ts
src/app/_features/resources/components/list/resourceslist.component.spec.ts
src/app/_features/resources/components/list/resourceslist.component.ts
src/app/_features/resources/components/search/search.component.spec.ts
src/app/_features/resources/pages/details/resource-details.page.spec.ts
src/app/_features/resources/resources.module.ts
src/app/_interceptors/mock-resources.interceptor.ts
src/app/_services/resources/resources.service.spec.ts
src/app/_services/resources/resources.service.ts
src/app/_shared/shared.module.ts
src/app/_shared/validators/resourceName.validator.spec.ts

See ticket here - https://jira.rax.io/browse/MNRVA-418
Add resources interceptor to resource services for mock environment to return mock data. This update makes the service unaware of the presence of the mock data but allows the interceptor to handle the response.
_Seeing some issues with the unit test for requests to the resources service_ 
`npm run test:unit` 

Refactor services with Resources interceptor for mock environment

---

src/app/_features/monitors/components/list/monitorslist.component.html
src/app/_features/monitors/components/list/monitorslist.component.scss
src/app/_features/monitors/components/list/monitorslist.component.spec.ts
src/app/_features/monitors/components/list/monitorslist.component.ts

**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-582
1) We need to show error and success icon according to the response coming from an api when you delete any monitor.
2) if monitor is deleted then the Alert icon should show in the modal popup
3) If a monitor is deleted then the Success icon should show in a modal popup.
**Testing:**
npm run test:unit
**Screenshots:
**

Delete monitor: tweak UI for modal pop  

---

package-lock.json
src/app/_features/resources/components/list/resourceslist.component.ts
src/app/_services/spinner/spinner.service.spec.ts
src/app/app.component.html
src/app/app.component.scss
src/index.html

See ticket here - https://jira.rax.io/browse/MNRVA-599
Resize overlay so that if a request timeouts the entire application is not blocked. Only the main app, the user should still have the ability to navigate.
Navigate to the Resources or Monitors.
Click sorting icon
Notice that clicking on navigation elements is still possible

Spinner resize overlay area

---

src/app/_features/monitors/components/list/monitorslist.component.html
src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts

See ticket here - https://jira.rax.io/browse/MNRVA-656
Monitor Scope and Type is added back, though the label is not needed for now. 

Bug mnrva 656

---

src/app/_features/visualize/pages/visualize.page/visualize.page.component.spec.ts
src/app/_features/visualize/pages/visualize.page/visualize.page.component.ts

See ticket here - https://jira.rax.io/browse/MNRVA-677
Removed metric service request from the `/visualize` feature view. We will be implementing a metrics service we just don't have these sets of endpoints at the time.
Navigate to `/visualize` page

Visual bug mnrva 677

---

src/app/_features/resources/components/list/resourceslist.component.html

See ticket here - https://jira.rax.io/browse/MNRVA-681
Since the _Suppression_ feature is not developed yet we'll hide the button along with _Create Multiple Monitors_
Navigate to Monitors list
To the left of the search box there should be no Suppression button

remove suppression & multiple monitors button

---

src/app/app.routing.ts

See ticket here - https://jira.rax.io/browse/MNRVA-711
Added default route of Visualize, meaning when the app is loaded the visualize route will be shown to users. 
Navigate to app 
The default route should be `/visualize`

Visualize route mnrva 711

---

env/environment.mock.ts
env/environment.prod.ts
env/environment.ts
projects/admin/src/app/_services/tenant/impersonation.service.spec.ts
src/app/_guards/feature-flag.guard.spec.ts
src/app/_guards/feature-flag.guard.ts
src/app/_services/config/environmentConfig.service.spec.ts
src/app/_services/features/featureFlag.service.spec.ts
src/app/_services/features/featureFlag.service.ts
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.routing.ts

**JIRA:**
See ticket here - https://jira.rax.io/browse/MNRVA-728
1) Create feature service and guard.
2) Call guard using canLoad property of routing which actually prevent any user to call route which is off.
3) Configure flags inside environment file and calling those into guard.
**Testing:**
**Screenshots:**

Implement Flagging service for features no longer being used

---

package-lock.json
package.json
src/app/_features/visualize/components/graphs/graphs.component.html
src/app/_features/visualize/components/graphs/graphs.component.ts
src/app/_shared/components/hedwig-graph/hedwig-graph.component.html
src/app/_shared/components/hedwig-graph/hedwig-graph.component.spec.ts
src/app/_shared/components/hedwig-graph/hedwig-graph.component.ts
src/app/_shared/shared.module.ts

See ticket here - https://jira.rax.io/browse/MNRVA-761
Add component for using Hedwig graphs - the component will be the single source of truth for the importing of the library. All instances of a graph will be using this component.
- Once on _visualize_ view there will be a graph in the right column
- `<hedwig-graph>` element will be present

Hedwig component mnrva 761
